"use client"

import Link from "next/link"
import { useEffect, useRef, useState } from "react"
import { Activity, AlertTriangle, Database, Download, RefreshCw } from "lucide-react"

type Status = { source:string;count:number;updatedAt:string|null;confirmation:string;recentActions:Array<{action:string;source:string;affectedCount:number;createdAt:string}>;postgres:{available:boolean;rowPresent:boolean;count:number;updatedAt:string|null};firestore:{configured:boolean;available:boolean;count:number;updatedAt:string|null};static:{count:number} }
type Action = "replace"|"clear-postgres"|"restore-demo"|"clear-firestore"
const formatDate=(value:string|null)=>value?new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"short"}).format(new Date(value)):"—"
const button="inline-flex min-h-11 items-center justify-center rounded-xl border border-border px-4 text-sm font-semibold transition-colors hover:bg-muted focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary"

export function QuestionBankSourceManager(){
  const [status,setStatus]=useState<Status|null>(null),[confirmation,setConfirmation]=useState(""),[pending,setPending]=useState<Action|null>(null)
  const [reviewedImport,setReviewedImport]=useState<unknown[]|null>(null),[message,setMessage]=useState(""),[error,setError]=useState("")
  const fileRef=useRef<HTMLInputElement>(null)
  const load=async()=>{setError("");try{const response=await fetch("/api/admin/question-bank",{cache:"no-store"});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error??"Unable to load source diagnostics.");setStatus(body)}catch(cause){setError(cause instanceof Error?cause.message:"Unable to load source diagnostics.")}}
  useEffect(()=>{void load()},[])
  const exportBank=async()=>{const response=await fetch("/api/admin/question-bank",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"export"})});if(!response.ok)return setMessage("Export failed.");const data=await response.json();const url=URL.createObjectURL(new Blob([JSON.stringify(data.questions,null,2)],{type:"application/json"}));const link=document.createElement("a");link.href=url;link.download=`mednexus-question-bank-${new Date().toISOString().slice(0,10)}.json`;link.click();URL.revokeObjectURL(url);setMessage(`Exported ${data.count} questions.`)}
  const refresh=async()=>{await fetch("/api/admin/question-bank",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"refresh"})});window.dispatchEvent(new Event("mednexus:questions-invalidated"));setMessage("Question cache refresh requested.");await load()}
  const run=async()=>{if(!pending||!status)return;const response=await fetch("/api/admin/question-bank",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:pending,confirmation,questions:pending==="replace"?reviewedImport:undefined})});const data=await response.json().catch(()=>({}));if(!response.ok)return setMessage(data.error??"Action failed.");window.dispatchEvent(new Event("mednexus:questions-invalidated"));setMessage(`Completed. ${data.count??""} question${data.count===1?"":"s"} now active.`);setPending(null);setConfirmation("");await load()}
  const ask=(action:Action)=>{if(action==="replace"&&!reviewedImport)return fileRef.current?.click();setPending(action);setMessage("")}
  if(!status)return <div className="rounded-xl border border-border bg-card p-6 text-sm text-muted-foreground">{error?<span className="flex items-center justify-between gap-3"><span>{error}</span><button onClick={()=>void load()} className="font-bold text-primary">Retry</button></span>:"Loading question-bank diagnostics…"}</div>
  const cards=[["PostgreSQL",status.postgres.available?"Available":"Unavailable",`Record ${status.postgres.rowPresent?"present":"empty"} · ${status.postgres.count} questions · ${formatDate(status.postgres.updatedAt)}`],["Firestore fallback",status.firestore.configured?(status.firestore.available?"Available":"Unavailable"):"Not configured",`${status.firestore.count} questions · ${formatDate(status.firestore.updatedAt)}`],["Bundled fallback","Available",`${status.static.count} demonstration questions`]]
  return <section className="max-w-5xl space-y-6"><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-primary">Platform diagnostics · Super admin</p><h1 className="mt-1 text-3xl font-bold">Question Bank Source</h1><p className="mt-2 max-w-3xl text-sm text-muted-foreground">See where learner MCQs are coming from and whether each fallback is healthy.</p></div><Link href="/admin/mcq" className="inline-flex min-h-11 items-center justify-center rounded-xl bg-primary px-4 text-sm font-bold text-primary-foreground">Manage MCQs</Link></header>
    <div className="grid gap-4 sm:grid-cols-3"><div className="rounded-xl border border-primary/20 bg-primary/5 p-5"><Database className="text-primary" size={20}/><p className="mt-3 text-xs font-semibold text-muted-foreground">Active source</p><p className="mt-1 text-xl font-bold capitalize">{status.source}</p></div><div className="rounded-xl border border-border bg-card p-5"><Activity className="text-emerald-500" size={20}/><p className="mt-3 text-xs font-semibold text-muted-foreground">Records served</p><p className="mt-1 text-xl font-bold">{status.count}</p></div><div className="rounded-xl border border-border bg-card p-5"><RefreshCw className="text-primary" size={20}/><p className="mt-3 text-xs font-semibold text-muted-foreground">Last source update</p><p className="mt-1 text-sm font-bold">{formatDate(status.updatedAt)}</p></div></div>
    <div className="grid gap-4 md:grid-cols-3">{cards.map(([name,state,detail])=><article key={name} className="rounded-xl border border-border bg-card p-5"><p className="font-semibold">{name}</p><p className={`mt-2 text-sm font-bold ${state==="Available"?"text-emerald-600":"text-warning"}`}>{state}</p><p className="mt-2 text-xs leading-5 text-muted-foreground">{detail}</p></article>)}</div>
    <div className="flex flex-wrap gap-3 rounded-xl border border-border bg-card p-5"><button onClick={()=>void exportBank()} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-primary px-4 text-sm font-semibold text-primary-foreground"><Download size={16}/>Export current bank</button><button onClick={()=>void refresh()} className={button}><RefreshCw size={16}/>Refresh diagnostics</button>{message&&<p className="w-full text-sm text-primary">{message}</p>}</div>
    <section className="rounded-xl border border-border bg-card p-5"><h2 className="font-semibold">Recent source audit</h2>{status.recentActions.length?<div className="mt-3 divide-y divide-border">{status.recentActions.map((item,index)=><div key={`${item.createdAt}-${index}`} className="flex flex-wrap justify-between gap-2 py-2 text-xs"><span className="capitalize">{item.action.replaceAll("-"," ")} · {item.source} · {item.affectedCount} records</span><time className="text-muted-foreground">{formatDate(item.createdAt)}</time></div>)}</div>:<p className="mt-2 text-sm text-muted-foreground">No recovery actions have been recorded.</p>}</section>
    <details className="rounded-xl border border-destructive/25 bg-card"><summary className="flex cursor-pointer list-none items-center gap-3 p-5 font-semibold text-destructive"><AlertTriangle size={18}/>Advanced recovery actions</summary><div className="border-t border-border p-5"><p className="text-sm text-muted-foreground">Use only for source recovery. Every destructive operation creates an automatic backup and audit entry before data changes, then invalidates question caches.</p><div className="mt-4 flex flex-wrap gap-3"><button onClick={()=>ask("replace")} className={button}>Replace from reviewed import</button><button onClick={()=>ask("restore-demo")} className={`${button} border-warning/60 text-warning`}>Restore bundled demo bank</button><button onClick={()=>ask("clear-postgres")} className={`${button} border-destructive/60 text-destructive`}>Clear database bank</button>{status.firestore.configured&&<button onClick={()=>ask("clear-firestore")} className={`${button} border-destructive/60 text-destructive`}>Clear Firestore fallback</button>}</div></div></details>
    <input ref={fileRef} type="file" accept="application/json" className="hidden" onChange={async event=>{const file=event.target.files?.[0];if(!file)return;try{const parsed:unknown=JSON.parse(await file.text());if(!Array.isArray(parsed))throw new Error();setReviewedImport(parsed);setPending("replace")}catch{setMessage("Choose a reviewed JSON array of questions.")}}}/>
    {pending&&<div className="rounded-xl border border-destructive/50 bg-destructive/10 p-6"><h2 className="font-semibold text-destructive">Confirm recovery action</h2><p className="mt-2 text-sm text-muted-foreground">Current source: <b>{status.source}</b> · {status.count} questions · {formatDate(status.updatedAt)}. An automatic backup and audit entry will be created first.</p><label className="mt-4 block text-sm text-muted-foreground">Type <b>{status.confirmation}</b><input value={confirmation} onChange={event=>setConfirmation(event.target.value)} className="mt-2 block w-full rounded-xl border border-border bg-background px-3 py-2 text-foreground"/></label><div className="mt-4 flex gap-3"><button onClick={()=>void run()} disabled={confirmation!==status.confirmation} className="rounded-xl bg-destructive px-4 py-2 text-sm font-bold text-destructive-foreground disabled:opacity-40">Confirm action</button><button onClick={()=>{setPending(null);setConfirmation("")}} className={button}>Cancel</button></div></div>}
  </section>
}
