"use client"

import { useEffect, useState } from "react"
import { ArrowLeft, ArrowRight, Bookmark, CheckCircle2, ChevronRight, FileText, NotebookPen, RotateCcw, Search, Sparkles } from "lucide-react"

type View = "Dashboard" | "Browse Questions" | "Bookmarks" | "My Notes" | "Revision Queue" | "Progress" | "Search"
type Collection = { id: string; title: string }
type Discipline = { id: string; collectionId: string; name: string }
type Set = { id: string; collectionId: string; disciplineId: string; name: string }
type Question = { id: string; collectionId: string; disciplineId: string; setId: string | null; prompt: string; modelAnswer: string; keyMarkingPoints: string[] }
type Data = { collections: Collection[]; disciplines: Discipline[]; sets: Set[]; questions: Question[] }
const empty: Data = { collections: [], disciplines: [], sets: [], questions: [] }

export function TheoryVault({ initialView = "Dashboard" }: { initialView?: View }) {
  const [view, setView] = useState<View>(initialView), [data, setData] = useState<Data>(empty), [loading, setLoading] = useState(true)
  const [trail, setTrail] = useState<{ collectionId?: string; disciplineId?: string; setId?: string }>({})
  const [currentId, setCurrentId] = useState<string | null>(null), [bookmarks, setBookmarks] = useState<string[]>([]), [revisions, setRevisions] = useState<string[]>([])
  const [completed, setCompleted] = useState<string[]>([]), [notes, setNotes] = useState<Record<string, string>>({}), [query, setQuery] = useState(""), [revealed, setRevealed] = useState(false)
  useEffect(() => { setView(initialView); setTrail({}); setCurrentId(null) }, [initialView])
  useEffect(() => { fetch("/api/theory").then(r => r.ok ? r.json() : empty).then(setData).catch(() => setData(empty)).finally(() => setLoading(false)) }, [])
  const collection = (id?: string) => data.collections.find(x => x.id === id)
  const discipline = (id?: string) => data.disciplines.find(x => x.id === id)
  const current = data.questions.find(q => q.id === currentId)
  const qForTrail = data.questions.filter(q => (!trail.collectionId || q.collectionId === trail.collectionId) && (!trail.disciplineId || q.disciplineId === trail.disciplineId) && (!trail.setId || q.setId === trail.setId))
  const open = (q: Question) => { setCurrentId(q.id); setTrail({ collectionId: q.collectionId, disciplineId: q.disciplineId, setId: q.setId ?? undefined }); setRevealed(false) }
  const pct = data.questions.length ? Math.round(completed.length / data.questions.length * 100) : 0
  const card = "rounded-2xl border border-border bg-card p-5 shadow-sm"
  const emptyState = <div className={`${card} py-12 text-center`}><FileText className="mx-auto text-primary" size={30}/><h2 className="mt-4 text-xl font-bold">Theory content is being prepared</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-muted-foreground">Your long-form clinical collections will appear here as soon as they are published. Browse Questions will be ready when your first collection arrives.</p></div>
  if (loading) return <div className={`${card} py-14 text-center text-sm text-muted-foreground`}>Opening Theory Vault…</div>
  if (!data.questions.length) return <div className="mx-auto max-w-6xl space-y-6"><Hero/>{emptyState}</div>
  if (current) return <Reader/>
  const metric = (label: string, value: string, icon: React.ReactNode) => <div className={`${card} p-4`}><div className="text-primary">{icon}</div><p className="mt-4 text-xl font-bold">{value}</p><p className="text-sm text-muted-foreground">{label}</p></div>
  const questionRow = (q: Question) => <button key={q.id} type="button" onClick={() => open(q)} className="flex w-full items-center justify-between gap-3 rounded-xl border border-border bg-card px-4 py-4 text-left hover:border-primary/45 hover:bg-primary/5"><div><p className="text-xs font-semibold text-primary">{collection(q.collectionId)?.title} · {discipline(q.disciplineId)?.name}</p><p className="mt-1 font-semibold">{q.prompt}</p></div><ChevronRight className="shrink-0 text-muted-foreground"/></button>
  const browse = () => {
    if (!trail.collectionId) return <Hierarchy title="Browse Questions" subtitle="Choose a collection to begin your reading path." items={data.collections.map(c => ({ id: c.id, title: c.title, meta: `${data.questions.filter(q => q.collectionId === c.id).length} questions` }))} onPick={id => setTrail({ collectionId: id })}/>
    if (!trail.disciplineId) { const ds = data.disciplines.filter(d => d.collectionId === trail.collectionId); return <Hierarchy title={collection(trail.collectionId)?.title ?? "Collections"} back={() => setTrail({})} items={ds.map(d => ({ id: d.id, title: d.name, meta: `${data.questions.filter(q => q.disciplineId === d.id).length} questions` }))} onPick={id => setTrail({ collectionId: trail.collectionId, disciplineId: id })}/> }
    const sets = data.sets.filter(s => s.disciplineId === trail.disciplineId)
    if (sets.length && !trail.setId) return <Hierarchy title={discipline(trail.disciplineId)?.name ?? "Discipline"} subtitle={collection(trail.collectionId)?.title} back={() => setTrail({ collectionId: trail.collectionId })} items={sets.map(s => ({ id: s.id, title: s.name, meta: `${data.questions.filter(q => q.setId === s.id).length} questions` }))} onPick={id => setTrail({ ...trail, setId: id })}/>
    return <div className="space-y-4"><Crumbs/><button type="button" onClick={() => setTrail({ collectionId: trail.collectionId, disciplineId: sets.length ? trail.disciplineId : undefined })} className="flex items-center gap-1 text-sm font-bold text-primary"><ArrowLeft size={16}/> Back</button><h2 className="text-2xl font-bold">{sets.length ? data.sets.find(s => s.id === trail.setId)?.name : discipline(trail.disciplineId)?.name}</h2><div className="space-y-2">{qForTrail.map(questionRow)}</div></div>
  }
  function Hero() { return <header className="overflow-hidden rounded-3xl border border-teal-300/25 bg-gradient-to-br from-teal-600 via-emerald-600 to-emerald-800 px-6 py-8 text-white shadow-lg sm:px-8"><div className="flex flex-wrap items-start justify-between gap-5"><div><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.2em] text-teal-100"><Sparkles size={15}/> Theory Vault</p><h1 className="mt-3 text-3xl font-bold tracking-tight">Read deliberately. Recall with confidence.</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-teal-50/90">Long-form clinical questions, model answers and a thoughtful revision trail for deep clinical learning.</p></div><div className="rounded-2xl border border-white/20 bg-white/10 px-4 py-3 text-sm"><span className="block text-teal-100">Current collection</span><b>{data.collections[0]?.title ?? "Theory Vault"}</b></div></div></header> }
  function Hierarchy({ title, subtitle, items, onPick, back }: { title: string; subtitle?: string; items: { id: string; title: string; meta: string }[]; onPick: (id: string) => void; back?: () => void }) { return <div className="space-y-4">{back && <button type="button" onClick={back} className="flex items-center gap-1 text-sm font-bold text-primary"><ArrowLeft size={16}/> Back</button>}<div><h2 className="text-2xl font-bold">{title}</h2>{subtitle && <p className="mt-1 text-sm text-muted-foreground">{subtitle}</p>}</div><div className="grid gap-4 md:grid-cols-2">{items.map(item => <button key={item.id} type="button" onClick={() => onPick(item.id)} className={`${card} text-left hover:border-primary/45`}><FileText className="text-primary"/><b className="mt-5 block text-lg">{item.title}</b><span className="mt-1 block text-sm text-muted-foreground">{item.meta} · explore at your own pace</span></button>)}</div></div> }
  function Crumbs() { return <p className="text-sm text-muted-foreground">{[collection(trail.collectionId)?.title, discipline(trail.disciplineId)?.name, data.sets.find(s => s.id === trail.setId)?.name].filter(Boolean).join(" · ")}</p> }
  if (view === "Dashboard") return <div className="mx-auto max-w-6xl space-y-6"><Hero/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metric("Continue reading", currentId ? "Resume" : "Start reading", <FileText size={20}/>)}{metric("Revisions due", `${revisions.length} due`, <RotateCcw size={20}/>)}{metric("Saved questions", String(bookmarks.length), <Bookmark size={20}/>)}{metric("Notes", String(Object.keys(notes).filter(id => notes[id]).length), <NotebookPen size={20}/>)}</div><div className="grid gap-5 lg:grid-cols-[1.35fr_1fr]"><div className={card}><p className="text-xs font-bold uppercase tracking-widest text-primary">Continue reading</p><h2 className="mt-2 text-xl font-bold">{data.questions[0].prompt}</h2><p className="mt-2 text-sm text-muted-foreground">{collection(data.questions[0].collectionId)?.title} · {discipline(data.questions[0].disciplineId)?.name}</p><button type="button" onClick={() => open(data.questions[0])} className="mt-5 rounded-xl bg-primary px-4 py-2.5 text-sm font-bold text-primary-foreground">Resume question</button></div><div className={card}><p className="text-xs font-bold uppercase tracking-widest text-primary">Theory progress</p><p className="mt-3 text-3xl font-bold">{pct}%</p><div className="mt-3 h-2 overflow-hidden rounded-full bg-muted"><div className="h-full bg-primary" style={{ width: `${pct}%` }}/></div><p className="mt-3 text-sm text-muted-foreground">{completed.length} of {data.questions.length} questions completed</p></div></div><div className="grid gap-5 md:grid-cols-2"><div className={card}><h2 className="font-bold">Collection progress</h2><div className="mt-4 space-y-3">{data.collections.map(c => <button key={c.id} onClick={() => { setView("Browse Questions"); setTrail({ collectionId: c.id }) }} className="flex w-full items-center justify-between text-left"><span><b className="block">{c.title}</b><small className="text-muted-foreground">{data.questions.filter(q => q.collectionId === c.id).length} questions</small></span><ChevronRight className="text-primary"/></button>)}</div></div><div className={card}><h2 className="font-bold">Start exploring</h2><p className="mt-2 text-sm text-muted-foreground">Move through collections, disciplines and focused sets.</p><button type="button" onClick={() => setView("Browse Questions")} className="mt-4 font-bold text-primary">Browse questions →</button></div></div></div>
  if (view === "Browse Questions") return <div className="mx-auto max-w-5xl">{browse()}</div>
  if (view === "Search") { const hits = data.questions.filter(q => q.prompt.toLowerCase().includes(query.toLowerCase())); return <div className="mx-auto max-w-5xl space-y-4"><h2 className="text-2xl font-bold">Search Theory</h2><label className="flex items-center gap-2 rounded-xl border border-border bg-card px-3"><Search size={18}/><input className="h-12 w-full bg-transparent outline-none" placeholder="Search prompts and disciplines" value={query} onChange={e => setQuery(e.target.value)}/></label><div className="space-y-2">{hits.map(questionRow)}</div></div> }
  const selected = view === "Bookmarks" ? data.questions.filter(q => bookmarks.includes(q.id)) : view === "My Notes" ? data.questions.filter(q => notes[q.id]) : view === "Revision Queue" ? data.questions.filter(q => revisions.includes(q.id)) : data.questions
  return <div className="mx-auto max-w-5xl space-y-4"><h2 className="text-2xl font-bold">{view === "Progress" ? "Theory progress" : view}</h2>{view === "Progress" && <div className={card}><p className="text-4xl font-bold text-primary">{completed.length}/{data.questions.length}</p><p className="mt-1 text-muted-foreground">questions read to completion</p></div>}{selected.length ? <div className="space-y-2">{selected.map(questionRow)}</div> : <div className={card}><b>Nothing here yet</b><p className="mt-1 text-sm text-muted-foreground">Build this space from the reader when you are ready.</p></div>}</div>
  function Reader() { if (!current) return null; const index = qForTrail.findIndex(q => q.id === current.id); const move = (offset: number) => qForTrail[index + offset] && open(qForTrail[index + offset]); return <div className="mx-auto max-w-4xl space-y-5"><button type="button" onClick={() => setCurrentId(null)} className="flex items-center gap-1 text-sm font-bold text-primary"><ArrowLeft size={16}/> Back to questions</button><Crumbs/><article className={card}><div className="flex justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-widest text-primary">Question {index + 1} of {qForTrail.length}</p><h1 className="mt-3 text-2xl font-bold leading-snug">{current.prompt}</h1></div><button type="button" aria-label="Bookmark" onClick={() => setBookmarks(x => x.includes(current.id) ? x.filter(id => id !== current.id) : [...x, current.id])} className="h-11 rounded-xl bg-muted p-3 text-primary"><Bookmark size={18}/></button></div><div className="mt-7 flex flex-wrap gap-2"><button type="button" onClick={() => setRevealed(x => !x)} className="rounded-xl bg-primary px-4 py-2.5 text-sm font-bold text-primary-foreground">{revealed ? "Hide model answer" : "Review model answer"}</button><button type="button" onClick={() => setRevisions(x => x.includes(current.id) ? x.filter(id => id !== current.id) : [...x, current.id])} className="rounded-xl border border-border px-4 py-2.5 text-sm font-bold">Revision</button><button type="button" onClick={() => setCompleted(x => x.includes(current.id) ? x : [...x, current.id])} className="rounded-xl border border-border px-4 py-2.5 text-sm font-bold">Complete</button></div>{revealed && <div className="mt-6 rounded-2xl border border-emerald-500/25 bg-emerald-500/5 p-5"><p className="text-xs font-bold uppercase tracking-widest text-emerald-700">Model answer</p><p className="mt-3 leading-7">{current.modelAnswer}</p><h2 className="mt-5 font-bold">Marking points</h2><ul className="mt-2 space-y-2">{current.keyMarkingPoints.map(point => <li key={point} className="flex gap-2 text-sm"><CheckCircle2 className="shrink-0 text-emerald-600" size={17}/>{point}</li>)}</ul></div>}<label className="mt-6 block text-sm font-bold">Your note<textarea value={notes[current.id] ?? ""} onChange={e => setNotes({ ...notes, [current.id]: e.target.value })} className="mt-2 min-h-24 w-full rounded-xl border border-border bg-background p-3 font-normal outline-none" placeholder="Capture a recall cue or clinical connection…"/></label></article><div className="flex justify-between">{index > 0 ? <button onClick={() => move(-1)} className="flex items-center gap-2 rounded-xl border border-border px-4 py-2.5 font-bold"><ArrowLeft size={17}/> Previous</button> : <span/>}{index < qForTrail.length - 1 && <button onClick={() => move(1)} className="flex items-center gap-2 rounded-xl bg-primary px-4 py-2.5 font-bold text-primary-foreground">Next <ArrowRight size={17}/></button>}</div></div> }
}
