"use client"

import { useEffect, useState } from "react"
import { useApp } from "@/contexts/app-context"
import { ArrowLeft, ArrowRight, Bookmark, CheckCircle2, ChevronRight, FileText, NotebookPen, RotateCcw, Search, Sparkles } from "lucide-react"

type View = "Dashboard" | "Browse Questions" | "Bookmarks" | "My Notes" | "Revision Queue" | "Progress" | "Search"
type Collection = { id: string; title: string }
type Discipline = { id: string; collectionId: string; name: string }
type Set = { id: string; collectionId: string; disciplineId: string; name: string }
type Question = { id: string; collectionId: string; disciplineId: string; setId: string | null; prompt: string; modelAnswer: string; keyMarkingPoints: string[] }
type Data = { collections: Collection[]; disciplines: Discipline[]; sets: Set[]; questions: Question[] }
type DashboardData = { displayName: string; totals: { total: number; completed: number }; collections: Array<{ id: string; title: string; disciplines: number; total: number; completed: number; lastStudiedDiscipline?: string }>; continueReading: ({ id: string; prompt: string; collection: string; discipline: string; setTitle?: string; position: number; setTotal: number; lastReadAt?: string } | null); revisions: { due: number; overdue: number; upcoming: number; next?: { prompt?: string } | null }; counts: { bookmarks: number; notes: number }; recentSets: Array<{ id: string; collection: string; discipline: string; setTitle: string; progressPercent: number; lastReadAt?: string }> }
const emptyDashboard = (displayName: string): DashboardData => ({ displayName, totals: { total: 0, completed: 0 }, collections: [], continueReading: null, revisions: { due: 0, overdue: 0, upcoming: 0 }, counts: { bookmarks: 0, notes: 0 }, recentSets: [] })
const dateLabel = (date?: string) => date ? new Intl.DateTimeFormat(undefined, { month: "short", day: "numeric" }).format(new Date(date)) : "Not opened yet"
function Snapshot({ icon, label, value, detail, onClick, urgent }: { icon: React.ReactNode; label: string; value: string; detail: string; onClick: () => void; urgent?: boolean }) { return <button onClick={onClick} className={`rounded-2xl border bg-card p-4 text-left shadow-sm transition hover:-translate-y-0.5 hover:border-primary/40 ${urgent ? "border-destructive/35" : "border-border"}`}><span className={urgent ? "text-destructive" : "text-primary"}>{icon}</span><p className="mt-4 truncate text-lg font-bold">{value}</p><p className="text-sm font-semibold">{label}</p><p className="mt-1 text-xs text-muted-foreground">{detail}</p></button>}
const empty: Data = { collections: [], disciplines: [], sets: [], questions: [] }

export function TheoryVault({ initialView = "Dashboard" }: { initialView?: View }) {
  const [view, setView] = useState<View>(initialView), [data, setData] = useState<Data>(empty), [loading, setLoading] = useState(false)
  const { user } = useApp()
  const [dashboard, setDashboard] = useState<DashboardData | null>(null)
  const [trail, setTrail] = useState<{ collectionId?: string; disciplineId?: string; setId?: string }>({})
  const [currentId, setCurrentId] = useState<string | null>(null), [bookmarks, setBookmarks] = useState<string[]>([]), [revisions, setRevisions] = useState<string[]>([])
  const [completed, setCompleted] = useState<string[]>([]), [notes, setNotes] = useState<Record<string, string>>({}), [query, setQuery] = useState(""), [revealed, setRevealed] = useState(false)
  useEffect(() => { setView(initialView); setTrail({}); setCurrentId(null) }, [initialView])
  useEffect(() => { const params = new URLSearchParams({ userId: user?.uid ?? "guest", name: user?.name ?? "Clinician" }); fetch(`/api/theory/dashboard?${params}`).then(r => r.ok ? r.json() : null).then(setDashboard).catch(() => setDashboard(null)) }, [user?.uid, user?.name])
  const collection = (id?: string) => data.collections.find(x => x.id === id)
  const discipline = (id?: string) => data.disciplines.find(x => x.id === id)
  const current = data.questions.find(q => q.id === currentId)
  const qForTrail = data.questions.filter(q => (!trail.collectionId || q.collectionId === trail.collectionId) && (!trail.disciplineId || q.disciplineId === trail.disciplineId) && (!trail.setId || q.setId === trail.setId))
  const loadContent = async () => { if (data.questions.length) return data; const response = await fetch("/api/theory"); const next = response.ok ? await response.json() as Data : empty; setData(next); return next }
  const open = (q: Question) => { setCurrentId(q.id); setTrail({ collectionId: q.collectionId, disciplineId: q.disciplineId, setId: q.setId ?? undefined }); setRevealed(false) }
  const pct = data.questions.length ? Math.round(completed.length / data.questions.length * 100) : 0
  const card = "rounded-2xl border border-border bg-card p-5 shadow-sm"
  const emptyState = <div className={`${card} py-12 text-center`}><FileText className="mx-auto text-primary" size={30}/><h2 className="mt-4 text-xl font-bold">Theory content is being prepared</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-muted-foreground">Your long-form clinical collections will appear here as soon as they are published. Browse Questions will be ready when your first collection arrives.</p></div>
  if (loading) return <div className={`${card} py-14 text-center text-sm text-muted-foreground`}>Opening Theory Vault…</div>
  if (current) return <Reader/>
  const metric = (label: string, value: string, icon: React.ReactNode) => <div className={`${card} p-4`}><div className="text-primary">{icon}</div><p className="mt-4 text-xl font-bold">{value}</p><p className="text-sm text-muted-foreground">{label}</p></div>
  const questionRow = (q: Question) => <button key={q.id} type="button" onClick={() => open(q)} className="flex w-full items-center justify-between gap-3 rounded-xl border border-border bg-card px-4 py-4 text-left hover:border-primary/45 hover:bg-primary/5"><div><p className="text-xs font-semibold text-primary">{collection(q.collectionId)?.title} · {discipline(q.disciplineId)?.name}</p><p className="mt-1 font-semibold">{q.prompt}</p></div><ChevronRight className="shrink-0 text-muted-foreground"/></button>
  const browse = () => {
    if (!trail.collectionId) return <Hierarchy title="Browse Questions" subtitle="Choose a collection to begin your reading path." items={data.collections.map(c => ({ id: c.id, title: c.title, meta: `${data.questions.filter(q => q.collectionId === c.id).length} questions` }))} onPick={id => setTrail({ collectionId: id })}/>
    if (!trail.disciplineId) { const ds = data.disciplines.filter(d => d.collectionId === trail.collectionId); return <Hierarchy title={collection(trail.collectionId)?.title ?? "Collections"} back={() => setTrail({})} items={ds.map(d => ({ id: d.id, title: d.name, meta: `${data.questions.filter(q => q.disciplineId === d.id).length} questions` }))} onPick={id => setTrail({ collectionId: trail.collectionId, disciplineId: id })}/> }
    const sets = data.sets.filter(s => s.disciplineId === trail.disciplineId)
    if (sets.length && !trail.setId) return <Hierarchy title={discipline(trail.disciplineId)?.name ?? "Discipline"} subtitle={collection(trail.collectionId)?.title} back={() => setTrail({ collectionId: trail.collectionId })} items={sets.map(s => ({ id: s.id, title: s.name, meta: `${data.questions.filter(q => q.setId === s.id).length} questions` }))} onPick={id => setTrail({ ...trail, setId: id })}/>
    return <div className="space-y-4"><Crumbs/><button type="button" onClick={() => setTrail({ collectionId: trail.collectionId, disciplineId: sets.length ? trail.disciplineId : undefined })} className="flex items-center gap-1 text-sm font-bold text-primary"><ArrowLeft size={16}/> Back</button><h2 className="text-2xl font-bold">{sets.length ? data.sets.find(s => s.id === trail.setId)?.name : discipline(trail.disciplineId)?.name}</h2><div className="space-y-2">{qForTrail.map(questionRow)}</div></div>
  }
  function Hero() { return <header className="overflow-hidden rounded-3xl border border-teal-300/25 bg-gradient-to-br from-teal-600 via-emerald-600 to-emerald-800 px-6 py-8 text-white shadow-lg sm:px-8"><div className="flex flex-wrap items-start justify-between gap-5"><div><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.2em] text-teal-100"><Sparkles size={15}/> Theory Vault</p><h1 className="mt-3 text-3xl font-bold tracking-tight">Read deliberately. Recall with confidence.</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-teal-50/90">Long-form clinical questions, model answers and a thoughtful revision trail for deep clinical learning.</p></div><div className="rounded-2xl border border-white/20 bg-white/10 px-4 py-3 text-sm"><span className="block text-teal-100">Current collection</span><b>{data.collections[0]?.title ?? "Theory Vault"}</b></div></div></header> }
  function Hierarchy({ title, subtitle, items, onPick, back }: { title: string; subtitle?: string; items: { id: string; title: string; meta: string }[]; onPick: (id: string) => void; back?: () => void }) { return <div className="space-y-4">{back && <button type="button" onClick={back} className="flex items-center gap-1 text-sm font-bold text-primary"><ArrowLeft size={16}/> Back</button>}<div><h2 className="text-2xl font-bold">{title}</h2>{subtitle && <p className="mt-1 text-sm text-muted-foreground">{subtitle}</p>}</div><div className="grid gap-4 md:grid-cols-2">{items.map(item => <button key={item.id} type="button" onClick={() => onPick(item.id)} className={`${card} text-left hover:border-primary/45`}><FileText className="text-primary"/><b className="mt-5 block text-lg">{item.title}</b><span className="mt-1 block text-sm text-muted-foreground">{item.meta} · explore at your own pace</span></button>)}</div></div> }
  function Crumbs() { return <p className="text-sm text-muted-foreground">{[collection(trail.collectionId)?.title, discipline(trail.disciplineId)?.name, data.sets.find(s => s.id === trail.setId)?.name].filter(Boolean).join(" · ")}</p> }
  if (view === "Dashboard") return <TheoryDashboard />
  function TheoryDashboard() {
    const d = dashboard ?? emptyDashboard(user?.name ?? "Clinician")
    const total = Number(d.totals.total), completedTotal = Number(d.totals.completed)
    const progress = total ? Math.round(completedTotal / total * 100) : 0
    const greeting = new Date().getHours() < 12 ? "Good morning" : new Date().getHours() < 18 ? "Good afternoon" : "Good evening"
    const go = (next: View) => { if (next === "Dashboard") { setView(next); return }; void loadContent().then(() => setView(next)) }
    const resume = () => { if (d.continueReading) { void loadContent().then(() => setCurrentId(d.continueReading!.id)) } else go("Browse Questions") }
    const browseCollection = (title: string) => { void loadContent().then(content => { const c = content.collections.find(c => c.title === title); if (c) setTrail({ collectionId: c.id }); setView("Browse Questions") }) }
    return <div className="mx-auto max-w-6xl space-y-6">
      <header className="overflow-hidden rounded-3xl border border-primary/20 bg-card px-5 py-6 shadow-sm sm:px-8 sm:py-8">
        <div className="flex flex-col gap-6 sm:flex-row sm:items-end sm:justify-between"><div><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.2em] text-primary"><Sparkles size={15}/>Theory Vault</p><h1 className="mt-3 text-3xl font-bold tracking-tight sm:text-4xl">{greeting}, {d.displayName}.</h1><p className="mt-2 text-lg font-semibold text-foreground">Read deliberately. Recall with confidence.</p><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">Build a durable clinical reading and revision practice, one thoughtful prompt at a time.</p></div><div className="flex flex-col gap-3 sm:items-end"><span className="inline-flex w-fit rounded-full border border-primary/25 bg-primary/10 px-3 py-1.5 text-sm font-semibold text-primary">{d.collections[0]?.title ?? "Theory Vault"}</span><p className="text-sm text-muted-foreground">{completedTotal} of {total} questions completed</p><div className="flex flex-wrap gap-2"><button onClick={resume} className="min-h-11 rounded-xl bg-primary px-4 text-sm font-bold text-primary-foreground shadow-sm transition hover:opacity-90">Continue reading</button><button onClick={() => go("Browse Questions")} className="min-h-11 rounded-xl border border-border px-4 text-sm font-bold transition hover:bg-muted">Browse questions</button></div></div></div>
      </header>
      <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <Snapshot icon={<FileText size={20}/>} label="Continue reading" value={d.continueReading ? d.continueReading.setTitle ?? "Resume set" : "Start reading"} detail={d.continueReading ? `Question ${d.continueReading.position} of ${d.continueReading.setTotal}` : "Choose a collection"} onClick={resume}/>
        <Snapshot icon={<RotateCcw size={20}/>} label="Revisions due" value={`${d.revisions.due ?? 0} due`} detail={d.revisions.overdue ? `${d.revisions.overdue} overdue` : "Keep your recall fresh"} urgent={Boolean(d.revisions.overdue)} onClick={() => go("Revision Queue")}/>
        <Snapshot icon={<Bookmark size={20}/>} label="Saved questions" value={String(d.counts.bookmarks ?? 0)} detail="Your bookmarks" onClick={() => go("Bookmarks")}/>
        <Snapshot icon={<NotebookPen size={20}/>} label="My notes" value={String(d.counts.notes ?? 0)} detail="Your clinical cues" onClick={() => go("My Notes")}/>
      </section>
      <section className="grid gap-5 lg:grid-cols-[1.35fr_1fr]">
        <article className={card}>{d.continueReading ? <><p className="text-xs font-bold uppercase tracking-[.18em] text-primary">Continue reading</p><h2 className="mt-3 line-clamp-3 text-xl font-bold leading-7">{d.continueReading.prompt}</h2><p className="mt-3 text-sm text-muted-foreground">{d.continueReading.collection} · {d.continueReading.discipline} · {d.continueReading.setTitle ?? "Reading set"}</p><p className="mt-2 text-sm text-muted-foreground">Question {d.continueReading.position} of {d.continueReading.setTotal} · Last opened {dateLabel(d.continueReading.lastReadAt)}</p><div className="mt-5 flex flex-wrap gap-3"><button onClick={resume} className="min-h-11 rounded-xl bg-primary px-4 text-sm font-bold text-primary-foreground">Resume question</button><button onClick={() => { void loadContent().then(() => go("Browse Questions")) }} className="min-h-11 rounded-xl border border-border px-4 text-sm font-bold hover:bg-muted">Open set</button></div></> : <><p className="text-xs font-bold uppercase tracking-[.18em] text-primary">Theory Vault</p><h2 className="mt-3 text-xl font-bold">Start your Theory Vault</h2><p className="mt-2 max-w-lg text-sm leading-6 text-muted-foreground">Explore End of Rotation reading as you progress, then return for End of Year consolidation and revision.</p><button onClick={() => go("Browse Questions")} className="mt-5 min-h-11 rounded-xl bg-primary px-4 text-sm font-bold text-primary-foreground">Browse collections</button></>}</article>
        <article className={card}><p className="text-xs font-bold uppercase tracking-[.18em] text-primary">Theory progress</p><div className="mt-3 flex items-end justify-between"><p className="text-4xl font-bold">{progress}%</p><p className="text-sm text-muted-foreground">{completedTotal} of {total} complete</p></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{width: `${progress}%`}}/></div><div className="mt-5 space-y-3">{d.collections.slice(0, 2).map(c => <button key={c.id} onClick={() => browseCollection(c.title)} className="flex w-full items-center justify-between rounded-xl px-2 py-2 text-left transition hover:bg-muted"><span><b className="block text-sm">{c.title}</b><small className="text-muted-foreground">{c.completed} of {c.total} complete</small></span><ChevronRight className="text-primary" size={18}/></button>)}</div></article>
      </section>
      <section><p className="mb-3 text-xs font-bold uppercase tracking-[.18em] text-primary">Collection progress</p><div className="grid gap-5 md:grid-cols-2">{["End of Rotation", "End of Year"].map(title => { const c = d.collections.find(c => c.title === title); const p = c?.total ? Math.round(Number(c.completed) / Number(c.total) * 100) : 0; return <article key={title} className={card}><FileText className="text-primary" size={21}/><h2 className="mt-5 text-xl font-bold">{title}</h2>{c ? <><p className="mt-2 text-sm text-muted-foreground">{c.disciplines} disciplines · {c.completed} of {c.total} questions completed</p><div className="mt-4 h-2 overflow-hidden rounded-full bg-muted"><div className="h-full bg-primary" style={{width:`${p}%`}}/></div><p className="mt-3 text-sm text-muted-foreground">{p}% progress{c.lastStudiedDiscipline ? ` · Last studied ${c.lastStudiedDiscipline}` : ""}</p></> : <p className="mt-2 text-sm text-muted-foreground">Content coming soon</p>}<button onClick={() => browseCollection(title)} className="mt-5 text-sm font-bold text-primary">Browse {title} →</button></article> })}</div></section>
      <section className="grid gap-5 lg:grid-cols-2"><article className={card}><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-primary">Recently studied sets</p><h2 className="mt-2 text-xl font-bold">Pick up where you left off</h2></div><button onClick={() => go("Progress")} className="text-sm font-bold text-primary">View all progress</button></div><div className="mt-4 divide-y divide-border">{d.recentSets.length ? d.recentSets.map(item => <div key={item.id} className="flex gap-3 py-3"><div className="min-w-0 flex-1"><p className="text-xs font-semibold text-primary">{item.collection} · {item.discipline}</p><p className="truncate font-semibold">{item.setTitle}</p><p className="text-xs text-muted-foreground">{item.progressPercent}% complete · {dateLabel(item.lastReadAt)}</p></div><button onClick={() => { void loadContent().then(() => setCurrentId(item.id)) }} className="self-center text-sm font-bold text-primary">Resume</button></div>) : <p className="py-5 text-sm text-muted-foreground">Your recently studied sets will appear here.</p>}</div></article><article className={card}><p className="text-xs font-bold uppercase tracking-[.18em] text-primary">Revision focus</p><h2 className="mt-2 text-xl font-bold">{d.revisions.due || d.revisions.overdue ? "Your next recall session" : "You are up to date"}</h2><div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-xl bg-muted p-3"><b className="text-xl">{d.revisions.due ?? 0}</b><span className="block text-xs text-muted-foreground">Due today</span></div><div className="rounded-xl bg-muted p-3"><b className={`text-xl ${d.revisions.overdue ? "text-destructive" : ""}`}>{d.revisions.overdue ?? 0}</b><span className="block text-xs text-muted-foreground">Overdue</span></div></div><p className="mt-4 text-sm text-muted-foreground">{d.revisions.next?.prompt ? `Next: ${d.revisions.next.prompt}` : `${d.revisions.upcoming ?? 0} upcoming revisions`}</p><button onClick={() => go("Revision Queue")} className="mt-5 min-h-11 rounded-xl border border-border px-4 text-sm font-bold hover:bg-muted">Open revision queue</button></article></section>
      <section className="flex flex-wrap gap-3 border-t border-border pt-6">{[["Browse Questions", "Browse Questions"], ["Search Theory", "Search"], ["Review Bookmarks", "Bookmarks"], ["Open My Notes", "My Notes"]].map(([label, target]) => <button key={label} onClick={() => go(target as View)} className="min-h-11 rounded-xl border border-border px-4 text-sm font-bold transition hover:border-primary/40 hover:bg-primary/5">{label}</button>)}</section>
    </div>
  }
  if (view === "Browse Questions") return <div className="mx-auto max-w-5xl">{browse()}</div>
  if (view === "Search") { const hits = data.questions.filter(q => q.prompt.toLowerCase().includes(query.toLowerCase())); return <div className="mx-auto max-w-5xl space-y-4"><h2 className="text-2xl font-bold">Search Theory</h2><label className="flex items-center gap-2 rounded-xl border border-border bg-card px-3"><Search size={18}/><input className="h-12 w-full bg-transparent outline-none" placeholder="Search prompts and disciplines" value={query} onChange={e => setQuery(e.target.value)}/></label><div className="space-y-2">{hits.map(questionRow)}</div></div> }
  const selected = view === "Bookmarks" ? data.questions.filter(q => bookmarks.includes(q.id)) : view === "My Notes" ? data.questions.filter(q => notes[q.id]) : view === "Revision Queue" ? data.questions.filter(q => revisions.includes(q.id)) : data.questions
  return <div className="mx-auto max-w-5xl space-y-4"><h2 className="text-2xl font-bold">{view === "Progress" ? "Theory progress" : view}</h2>{view === "Progress" && <div className={card}><p className="text-4xl font-bold text-primary">{completed.length}/{data.questions.length}</p><p className="mt-1 text-muted-foreground">questions read to completion</p></div>}{selected.length ? <div className="space-y-2">{selected.map(questionRow)}</div> : <div className={card}><b>Nothing here yet</b><p className="mt-1 text-sm text-muted-foreground">Build this space from the reader when you are ready.</p></div>}</div>
  function Reader() { if (!current) return null; const index = qForTrail.findIndex(q => q.id === current.id); const move = (offset: number) => qForTrail[index + offset] && open(qForTrail[index + offset]); return <div className="mx-auto max-w-4xl space-y-5"><button type="button" onClick={() => setCurrentId(null)} className="flex items-center gap-1 text-sm font-bold text-primary"><ArrowLeft size={16}/> Back to questions</button><Crumbs/><article className={card}><div className="flex justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-widest text-primary">Question {index + 1} of {qForTrail.length}</p><h1 className="mt-3 text-2xl font-bold leading-snug">{current.prompt}</h1></div><button type="button" aria-label="Bookmark" onClick={() => setBookmarks(x => x.includes(current.id) ? x.filter(id => id !== current.id) : [...x, current.id])} className="h-11 rounded-xl bg-muted p-3 text-primary"><Bookmark size={18}/></button></div><div className="mt-7 flex flex-wrap gap-2"><button type="button" onClick={() => setRevealed(x => !x)} className="rounded-xl bg-primary px-4 py-2.5 text-sm font-bold text-primary-foreground">{revealed ? "Hide model answer" : "Review model answer"}</button><button type="button" onClick={() => setRevisions(x => x.includes(current.id) ? x.filter(id => id !== current.id) : [...x, current.id])} className="rounded-xl border border-border px-4 py-2.5 text-sm font-bold">Revision</button><button type="button" onClick={() => setCompleted(x => x.includes(current.id) ? x : [...x, current.id])} className="rounded-xl border border-border px-4 py-2.5 text-sm font-bold">Complete</button></div>{revealed && <div className="mt-6 rounded-2xl border border-emerald-500/25 bg-emerald-500/5 p-5"><p className="text-xs font-bold uppercase tracking-widest text-emerald-700">Model answer</p><p className="mt-3 leading-7">{current.modelAnswer}</p><h2 className="mt-5 font-bold">Marking points</h2><ul className="mt-2 space-y-2">{current.keyMarkingPoints.map(point => <li key={point} className="flex gap-2 text-sm"><CheckCircle2 className="shrink-0 text-emerald-600" size={17}/>{point}</li>)}</ul></div>}<label className="mt-6 block text-sm font-bold">Your note<textarea value={notes[current.id] ?? ""} onChange={e => setNotes({ ...notes, [current.id]: e.target.value })} className="mt-2 min-h-24 w-full rounded-xl border border-border bg-background p-3 font-normal outline-none" placeholder="Capture a recall cue or clinical connection…"/></label></article><div className="flex justify-between">{index > 0 ? <button onClick={() => move(-1)} className="flex items-center gap-2 rounded-xl border border-border px-4 py-2.5 font-bold"><ArrowLeft size={17}/> Previous</button> : <span/>}{index < qForTrail.length - 1 && <button onClick={() => move(1)} className="flex items-center gap-2 rounded-xl bg-primary px-4 py-2.5 font-bold text-primary-foreground">Next <ArrowRight size={17}/></button>}</div></div> }
}
