"use client"

import Link from "next/link"
import { Archive, BookOpen, ClipboardCheck, FileUp, FolderTree, Layers3, Settings2, Users, Bell, Megaphone } from "lucide-react"
import { useAdmin } from "@/contexts/admin-context"

const workspaces = [
  ["Manage Collections", "Create and order End of Rotation and End of Year collections.", "/admin/theory/collections", FolderTree],
  ["Manage Disciplines", "Maintain the clinical disciplines within each collection.", "/admin/theory/disciplines", Layers3],
  ["Manage Sets", "Group questions into focused, optional reading sets.", "/admin/theory/sets", Archive],
  ["Question Library", "Search, inspect and edit long-form Theory questions.", "/admin/theory/questions", BookOpen],
  ["Import Questions", "Validate a bulk import before it enters the review queue.", "/admin/theory/import", FileUp],
  ["Review & Publish", "Resolve validation issues and move drafts through publication.", "/admin/theory/review", ClipboardCheck],
] as const

export function TheoryAdminHome({ section }: { section?: string }) {
  const { isAdmin } = useAdmin()
  const title = section ? section.replaceAll("-", " ").replace(/\b\w/g, x => x.toUpperCase()) : "Theory Vault Administration"
  if (!isAdmin) return <main className="mx-auto max-w-xl p-8"><div className="rounded-3xl border border-border bg-card p-7 text-center"><h1 className="text-2xl font-bold">Admin access required</h1><p className="mt-2 text-sm text-muted-foreground">Theory administration is available to verified MedNexus administrators only.</p><Link href="/" className="mt-5 inline-block rounded-xl bg-primary px-4 py-2.5 text-sm font-bold text-primary-foreground">Return to MedNexus</Link></div></main>
  if (section) return <main className="mx-auto max-w-5xl p-5 md:p-8"><Link href="/admin/theory" className="text-sm font-bold text-primary">← Theory Vault Administration</Link><div className="mt-5 rounded-3xl border border-border bg-card p-7"><p className="text-xs font-bold uppercase tracking-widest text-primary">Focused workspace</p><h1 className="mt-2 text-3xl font-bold">{title}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-muted-foreground">This dedicated workspace keeps Theory hierarchy, authoring, import, review and publishing tasks separate. Connect its controls to the Theory API as editorial workflows are enabled.</p></div></main>
  return <main className="mx-auto max-w-6xl space-y-6 p-5 md:p-8"><header className="rounded-3xl border border-teal-500/20 bg-gradient-to-br from-teal-700 to-emerald-800 p-7 text-white"><p className="text-xs font-bold uppercase tracking-[.18em] text-teal-100">Theory Vault</p><h1 className="mt-2 text-3xl font-bold">Theory Vault Administration</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-teal-50/90">Manage long-form clinical learning content without mixing it into the MCQ Q-Bank.</p></header><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{[["Collections", "0"], ["Disciplines", "0"], ["Sets", "0"], ["Drafts awaiting review", "0"], ["Published questions", "0"]].map(([label, value]) => <div key={label} className="rounded-2xl border border-border bg-card p-4"><p className="text-2xl font-bold text-primary">{value}</p><p className="mt-1 text-sm text-muted-foreground">{label}</p></div>)}</section><section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{workspaces.map(([name, description, href, Icon]) => <Link key={name} href={href} className="rounded-2xl border border-border bg-card p-5 transition hover:border-primary/45 hover:bg-primary/5"><Icon className="text-primary" size={22}/><h2 className="mt-5 font-bold">{name}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{description}</p></Link>)}</section><section className="grid gap-4 lg:grid-cols-2"><div className="rounded-2xl border border-border bg-card p-5"><h2 className="font-bold">Recent activity & import status</h2><p className="mt-2 text-sm text-muted-foreground">No recent Theory imports or publication activity.</p></div><div className="rounded-2xl border border-border bg-card p-5"><h2 className="font-bold">Shared admin tools</h2><div className="mt-4 flex flex-wrap gap-3">{[["Users", "/", Users], ["Broadcasts", "/", Megaphone], ["Notifications", "/notifications", Bell], ["Platform Settings", "/", Settings2]].map(([label, href, Icon]) => <Link key={label as string} href={href as string} className="inline-flex items-center gap-2 rounded-xl bg-muted px-3 py-2 text-sm font-semibold"><Icon size={16}/>{label as string}</Link>)}</div></div></section></main>
}
