// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/auth-screen/Elevated.tsx": () => import("../components/mockups/auth-screen/Elevated.tsx"),
  "./components/mockups/auth-screen/Structured.tsx": () => import("../components/mockups/auth-screen/Structured.tsx")
};
