"use client"

import { useEffect, useMemo, useState } from "react"
import Link from "next/link"
import { ArrowLeft, Archive, ArrowDown, ArrowUp, Plus, Search, ShieldAlert } from "lucide-react"
import { useAdmin } from "@/contexts/admin-context"

type Row = { id: string; title?: string; collection_id?: string; discipline_id?: string; set_id?: string | null; prompt?: string; model_answer?: string; category?: string; module?: string; set_number?: number; tags?: string[]; source_metadata?: unknown; past_paper_metadata?: unknown; data?: { criticalFlags?: string[]; revisionRelevance?: string }; publication_status?: string; is_archived?: boolean; sort_order?: number }
type Form = { id?: string; collectionId: string; disciplineId: string; setId: string; prompt: string; modelAnswer: string; markingPoints: string; criticalFlags: string; tags: string; category: string; module: string; setNumber: string; sourceMetadata: string; pastPaperMetadata: string; revisionRelevance: string; difficulty: string; estimatedStudyMinutes: string; sortOrder: string; publicationStatus: string }
const blank = (): Form => ({ collectionId: "", disciplineId: "", setId: "", prompt: "", modelAnswer: "", markingPoints: "", criticalFlags: "", tags: "", category: "", module: "", setNumber: "1", sourceMetadata: "{}", pastPaperMetadata: "[]", revisionRelevance: "", difficulty: "medium", estimatedStudyMinutes: "5", sortOrder: "0", publicationStatus: "draft" })
const headers = (token: string | null) => ({ "Content-Type": "application/json", ...(token ? { "x-admin-token": token } : {}) })
const parseJson = (value: string, fallback: unknown) => { try { return JSON.parse(value) } catch { return fallback } }

export function TheoryVaultEditor() {
  const { isAdmin, adminReady, adminToken } = useAdmin()
  const [collections, setCollections] = useState<Row[]>([]); const [disciplines, setDisciplines] = useState<Row[]>([]); const [sets, setSets] = useState<Row[]>([]); const [questions, setQuestions] = useState<Row[]>([])
  const [form, setForm] = useState<Form>(blank()); const [query, setQuery] = useState(""); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false)
  const load = async () => { if (!adminToken) return; try { const read = async (resource: string) => { const response = await fetch(`/api/theory/admin/${resource}`, { headers: headers(adminToken) }); const body = await response.json(); if (!response.ok) throw Error(body.error); return body[resource] as Row[] }; const [c, d, s, q] = await Promise.all(["collections", "disciplines", "sets", "questions"].map(read)); setCollections(c); setDisciplines(d); setSets(s); setQuestions(q) } catch (error) { setNotice(error instanceof Error ? error.message : "Unable to load Theory records.") } }
  useEffect(() => { load() }, [adminToken]) // eslint-disable-line react-hooks/exhaustive-deps
  const disciplinesForForm = useMemo(() => disciplines.filter(row => row.collection_id === form.collectionId), [disciplines, form.collectionId])
  const setsForForm = useMemo(() => sets.filter(row => row.discipline_id === form.disciplineId), [sets, form.disciplineId])
  const visibleQuestions = useMemo(() => { const term = query.trim().toLowerCase(); return !term ? questions : questions.filter(q => [q.prompt, q.model_answer, q.category, q.module, ...(q.tags || [])].filter(Boolean).join(" ").toLowerCase().includes(term)) }, [questions, query])
  const update = <K extends keyof Form>(key: K, value: Form[K]) => setForm(current => ({ ...current, [key]: value }))
  const request = async (url: string, method: string, body: object) => { const response = await fetch(url, { method, headers: headers(adminToken), body: JSON.stringify(body) }); const data = await response.json(); if (!response.ok) throw Error(data.error || "Theory request failed"); return data }
  const createHierarchy = async (resource: "collections" | "disciplines" | "sets") => { const title = window.prompt(`Name this Theory ${resource.slice(0, -1)}:`)?.trim(); if (!title) return; const parent = resource === "collections" ? {} : resource === "disciplines" ? { collectionId: form.collectionId } : { collectionId: form.collectionId, disciplineId: form.disciplineId }; if (resource !== "collections" && !form.collectionId) return setNotice("Choose a collection first."); if (resource === "sets" && !form.disciplineId) return setNotice("Choose a discipline first."); setBusy(true); try { await request(`/api/theory/admin/${resource}`, "POST", { title, ...parent }); await load(); setNotice(`${title} created.`) } catch (e) { setNotice(e instanceof Error ? e.message : "Could not create hierarchy item.") } finally { setBusy(false) } }
  const save = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); const payload = { ...form, setId: form.setId || null, setNumber: Number(form.setNumber), estimatedStudyMinutes: Number(form.estimatedStudyMinutes), sortOrder: Number(form.sortOrder), markingPoints: form.markingPoints.split("\n").map(x => x.trim()).filter(Boolean), criticalFlags: form.criticalFlags.split("\n").map(x => x.trim()).filter(Boolean), tags: form.tags.split(",").map(x => x.trim()).filter(Boolean), sourceMetadata: parseJson(form.sourceMetadata, {}), pastPaperMetadata: parseJson(form.pastPaperMetadata, []), data: { criticalFlags: form.criticalFlags.split("\n").map(x => x.trim()).filter(Boolean), revisionRelevance: form.revisionRelevance } }; try { await request("/api/theory/admin/questions", form.id ? "PATCH" : "POST", payload); setNotice(form.id ? "Theory question updated." : "Theory question created for review."); setForm(blank()); await load() } catch (e) { setNotice(e instanceof Error ? e.message : "Save failed.") } finally { setBusy(false) } }
  const edit = (q: Row) => setForm({ id: q.id, collectionId: q.collection_id || "", disciplineId: q.discipline_id || "", setId: q.set_id || "", prompt: q.prompt || "", modelAnswer: q.model_answer || "", markingPoints: "", criticalFlags: q.data?.criticalFlags?.join("\n") || "", tags: (q.tags || []).join(", "), category: q.category || "", module: q.module || "", setNumber: String(q.set_number || 1), sourceMetadata: JSON.stringify(q.source_metadata || {}, null, 2), pastPaperMetadata: JSON.stringify(q.past_paper_metadata || [], null, 2), revisionRelevance: q.data?.revisionRelevance || "", difficulty: "medium", estimatedStudyMinutes: "5", sortOrder: String(q.sort_order || 0), publicationStatus: q.publication_status || "draft" })
  const action = async (q: Row, kind: "publish" | "archive" | "up" | "down") => { setBusy(true); try { if (kind === "publish") await request("/api/theory/admin/publishing", "POST", { type: "question", id: q.id, published: q.publication_status !== "published" }); else if (kind === "archive") await request("/api/theory/admin/archiving", "POST", { id: q.id, archived: !q.is_archived }); else { const ids = [...questions].sort((a,b) => (a.sort_order || 0) - (b.sort_order || 0)); const at = ids.findIndex(item => item.id === q.id), other = ids[at + (kind === "up" ? -1 : 1)]; if (other) [ids[at], ids[at + (kind === "up" ? -1 : 1)]] = [other, q]; await request("/api/theory/admin/ordering", "POST", { type: "question", ids: ids.map(item => item.id) }) } await load() } catch (e) { setNotice(e instanceof Error ? e.message : "Workflow failed.") } finally { setBusy(false) } }
  if (!adminReady) return <main className="p-8">Loading admin workspace…</main>
  if (!isAdmin) return <main className="mx-auto max-w-xl p-8"><div className="rounded-2xl border border-amber-500/30 bg-card p-6"><ShieldAlert className="text-amber-600"/><h1 className="mt-3 text-xl font-bold">Verified admin access required</h1><p className="mt-2 text-sm text-muted-foreground">Theory records are restricted to authenticated administrators.</p><Link href="/theory" className="mt-5 inline-flex text-sm font-bold text-primary">Return to Theory Vault</Link></div></main>
  return <main className="min-h-screen bg-background p-4 text-foreground md:p-8"><div className="mx-auto max-w-7xl space-y-6"><header className="flex flex-wrap items-center justify-between gap-3"><div><Link href="/theory" className="inline-flex items-center gap-1 text-sm text-muted-foreground"><ArrowLeft size={15}/>Theory Vault</Link><h1 className="mt-2 text-3xl font-bold">Theory question administration</h1><p className="mt-1 text-sm text-muted-foreground">Create, review, publish, archive, categorize, and order records in <code>mednexus_theory_questions</code>.</p></div><button onClick={() => setForm(blank())} className="inline-flex items-center gap-2 rounded-xl border bg-card px-4 py-2 text-sm font-bold"><Plus size={16}/>New question</button></header>{notice && <p role="status" className="rounded-xl border bg-card px-4 py-3 text-sm">{notice}</p>}
  <section className="grid gap-4 md:grid-cols-3">{([["Collections", collections, "collections"], ["Disciplines", disciplines, "disciplines"], ["Sets", sets, "sets"]] as const).map(([label, rows, resource]) => <div className="rounded-2xl border bg-card p-4" key={label}><div className="flex justify-between"><h2 className="font-bold">{label}</h2><button disabled={busy} onClick={() => createHierarchy(resource)} aria-label={`Add ${label}`}><Plus size={18}/></button></div><p className="mt-2 text-sm text-muted-foreground">{rows.length} configured</p></div>)}</section>
  <section className="grid gap-6 lg:grid-cols-[1.15fr_.85fr]"><form onSubmit={save} className="space-y-4 rounded-2xl border bg-card p-5"><div><h2 className="font-bold">{form.id ? "Edit" : "New"} Theory question</h2><p className="text-sm text-muted-foreground">Required study content is separate from MCQ authoring.</p></div><div className="grid gap-3 sm:grid-cols-3"><Select label="Collection" rows={collections} value={form.collectionId} onChange={v => setForm(x => ({ ...x, collectionId: v, disciplineId: "", setId: "" }))}/><Select label="Discipline" rows={disciplinesForForm} value={form.disciplineId} onChange={v => setForm(x => ({ ...x, disciplineId: v, setId: "" }))}/><Select label="Set" rows={setsForForm} value={form.setId} optional onChange={v => update("setId", v)}/></div><div className="grid gap-3 sm:grid-cols-3"><Field label="Category" value={form.category} onChange={v => update("category",v)}/><Field label="Module" value={form.module} onChange={v => update("module",v)}/><Field label="Set number" value={form.setNumber} onChange={v => update("setNumber",v)}/></div><Field label="Prompt" area value={form.prompt} onChange={v => update("prompt",v)}/><Field label="Model answer" area value={form.modelAnswer} onChange={v => update("modelAnswer",v)}/><div className="grid gap-3 sm:grid-cols-2"><Field label="Critical flags (one per line)" area value={form.criticalFlags} onChange={v => update("criticalFlags",v)}/><Field label="Revision relevance" area value={form.revisionRelevance} onChange={v => update("revisionRelevance",v)}/></div><div className="grid gap-3 sm:grid-cols-2"><Field label="Tags (comma-separated)" value={form.tags} onChange={v => update("tags",v)}/><Field label="Source metadata (JSON)" area value={form.sourceMetadata} onChange={v => update("sourceMetadata",v)}/><Field label="Past-paper metadata (JSON)" area value={form.pastPaperMetadata} onChange={v => update("pastPaperMetadata",v)}/><Field label="Marking points (one per line)" area value={form.markingPoints} onChange={v => update("markingPoints",v)}/></div><div className="grid gap-3 sm:grid-cols-4"><Field label="Minutes" value={form.estimatedStudyMinutes} onChange={v => update("estimatedStudyMinutes",v)}/><Field label="Order" value={form.sortOrder} onChange={v => update("sortOrder",v)}/><Select label="Difficulty" rows={[{id:"easy",title:"Easy"},{id:"medium",title:"Medium"},{id:"hard",title:"Hard"},{id:"expert",title:"Expert"}]} value={form.difficulty} onChange={v=>update("difficulty",v)}/><Select label="Review status" rows={[{id:"draft",title:"Draft"},{id:"unpublished",title:"Review"},{id:"published",title:"Published"}]} value={form.publicationStatus} onChange={v=>update("publicationStatus",v)}/></div><button disabled={busy} className="rounded-xl bg-primary px-4 py-2.5 text-sm font-bold text-primary-foreground disabled:opacity-50">{form.id ? "Save edits" : "Create draft"}</button></form>
  <section className="rounded-2xl border bg-card p-5"><div className="flex items-center justify-between gap-3"><div><h2 className="font-bold">Review queue</h2><p className="text-sm text-muted-foreground">{visibleQuestions.length} Theory records</p></div><label className="relative"><Search className="absolute left-3 top-2.5 text-muted-foreground" size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search prompts, tags…" className="rounded-lg border bg-background py-2 pl-9 pr-3 text-sm"/></label></div><div className="mt-4 max-h-[48rem] space-y-2 overflow-auto">{visibleQuestions.map(q=><article key={q.id} className="rounded-xl border p-3"><p className="line-clamp-2 text-sm font-semibold">{q.prompt}</p><p className="mt-1 text-xs text-muted-foreground">{q.publication_status || "draft"} · {q.is_archived ? "archived" : "active"} · order {q.sort_order || 0}</p><div className="mt-3 flex flex-wrap gap-2"><button onClick={()=>edit(q)} className="rounded-lg border px-2 py-1 text-xs font-semibold">Edit</button><button disabled={busy} onClick={()=>action(q,"publish")} className="rounded-lg border px-2 py-1 text-xs font-semibold">{q.publication_status === "published" ? "Unpublish" : "Publish"}</button><button disabled={busy} onClick={()=>action(q,"archive")} className="rounded-lg border px-2 py-1 text-xs font-semibold"><Archive className="mr-1 inline" size={12}/>{q.is_archived ? "Restore" : "Archive"}</button><button disabled={busy} onClick={()=>action(q,"up")} aria-label="Move question up" className="rounded-lg border p-1"><ArrowUp size={13}/></button><button disabled={busy} onClick={()=>action(q,"down")} aria-label="Move question down" className="rounded-lg border p-1"><ArrowDown size={13}/></button></div></article>)}</div></section></section></div></main>
}
function Select({label,rows,value,onChange,optional=false}:{label:string;rows:Row[];value:string;onChange:(v:string)=>void;optional?:boolean}){return <label className="text-sm font-medium">{label}<select required={!optional} value={value} onChange={e=>onChange(e.target.value)} className="mt-1 w-full rounded-lg border bg-background px-3 py-2"><option value="">{optional?"No set":"Select"}</option>{rows.map(row=><option key={row.id} value={row.id}>{row.title}</option>)}</select></label>}
function Field({label,value,onChange,area=false}:{label:string;value:string;onChange:(v:string)=>void;area?:boolean}){return <label className="block text-sm font-medium">{label}{area?<textarea required={label==="Prompt"||label==="Model answer"} value={value} onChange={e=>onChange(e.target.value)} className="mt-1 min-h-24 w-full rounded-lg border bg-background px-3 py-2"/>:<input value={value} onChange={e=>onChange(e.target.value)} className="mt-1 w-full rounded-lg border bg-background px-3 py-2"/>}</label>}
