"use client"

import Link from "next/link"
import { useEffect, useState } from "react"
import { ArrowRight, BookOpen, CalendarClock, FileText, Search, Star } from "lucide-react"
import { LoadingState, ErrorState } from "./RevisionQueueView"

type Item = { id: string; prompt: string; collection_id: string; discipline_id: string; set_id: string | null; collection_title?: string; discipline_title?: string; set_title?: string; occurred_at?: string }
type Level = { collection_id: string; collection_title: string; discipline_id: string; discipline_title: string; set_id: string | null; set_title: string | null; total: number; read: number; completed: number; model_answer_reviews: number; revision_completed: number; saved: number; notes: number; recent_activity: string | null }
type Data = { summary: { total: number; read: number; completed: number; model_answer_reviews: number; saved: number; notes: number; due_today: number }; hierarchy: Level[]; recent: Item[]; continue: Item | null }
const auth = (): Record<string, string> => typeof window === "undefined" ? {} : localStorage.getItem("mednexus-guest-token") ? { "x-guest-token": localStorage.getItem("mednexus-guest-token")! } : localStorage.getItem("mednexus-user-token") ? { "x-session-token": localStorage.getItem("mednexus-user-token")! } : {}
const href = (x: Pick<Item, "collection_id" | "discipline_id" | "set_id">) => `/theory/reader?${new URLSearchParams({ collectionId: x.collection_id, disciplineId: x.discipline_id, ...(x.set_id ? { setId: x.set_id } : {}) })}`
const crumbs = (x: Pick<Item, "collection_title" | "discipline_title" | "set_title">) => [x.collection_title, x.discipline_title, x.set_title].filter(Boolean).join(" · ")

export function TheoryDashboard() {
  const [data, setData] = useState<Data | null>(null); const [error, setError] = useState<string | null>(null)
  useEffect(() => { fetch("/api/theory/dashboard", { headers: auth() }).then(async r => { const d = await r.json(); if (!r.ok) throw Error(d.error || "Failed to load dashboard."); setData(d) }).catch(e => setError(e.message)) }, [])
  if (error) return <ErrorState message={error} />
  if (!data) return <LoadingState />
  const rotation = data.hierarchy.filter(x => x.collection_id === "end_of_rotation"), year = data.hierarchy.filter(x => x.collection_id === "end_of_year")
  const statColor: Record<string, string> = { teal: "text-teal-700 dark:text-teal-300", violet: "text-violet-700 dark:text-violet-300", amber: "text-amber-700 dark:text-amber-300", rose: "text-rose-700 dark:text-rose-300" }
  const progress = (items: Level[]) => { const total = items.reduce((n, x) => n + x.total, 0); const completed = items.reduce((n, x) => n + x.completed, 0); return total ? Math.round(completed / total * 100) : 0 }
  return <div className="mx-auto max-w-6xl space-y-7">
    <section className="rounded-3xl border border-teal-200/70 bg-gradient-to-br from-teal-50 via-white to-amber-50 p-6 shadow-sm dark:border-teal-800/40 dark:from-teal-950/25 dark:via-background dark:to-amber-950/20 sm:p-8">
      <p className="text-xs font-bold uppercase tracking-[0.18em] text-teal-700 dark:text-teal-300">Theory Vault</p><h1 className="mt-2 text-3xl font-extrabold tracking-tight">Return to the reasoning that matters.</h1>
      <p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">Read, review model answers, and retain long-form clinical knowledge—without MCQ scores or exam-game statistics.</p>
      <div className="mt-5 flex flex-wrap gap-3"><Link href="/theory/browse" className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-teal-700 px-4 text-sm font-bold text-white transition-colors hover:bg-teal-800"><BookOpen size={17}/>Browse questions</Link><Link href="/theory/search" className="inline-flex min-h-11 items-center gap-2 rounded-xl border bg-card px-4 text-sm font-bold hover:bg-muted"><Search size={17}/>Search vault</Link></div>
    </section>
    <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
      {[["Questions completed",data.summary.completed,"teal"],["Model answers reviewed",data.summary.model_answer_reviews,"violet"],["Due today",data.summary.due_today,"amber"],["Personal notes",data.summary.notes,"rose"]].map(([label,value,color]) => <div key={String(label)} className="rounded-2xl border bg-card p-4"><p className={`text-2xl font-extrabold ${statColor[String(color)]}`}>{value}</p><p className="mt-1 text-xs font-semibold text-muted-foreground">{label}</p></div>)}
    </section>
    <section className="grid gap-4 lg:grid-cols-2">
      <div className="rounded-2xl border bg-card p-5"><p className="text-xs font-bold uppercase tracking-widest text-muted-foreground">Continue studying</p>{data.continue ? <Link href={href(data.continue)} className="mt-3 block rounded-xl border border-teal-200 bg-teal-50/60 p-4 transition-colors hover:bg-teal-100/70 dark:border-teal-800 dark:bg-teal-950/20"><p className="text-[11px] font-bold text-teal-700 dark:text-teal-300">{crumbs(data.continue)}</p><p className="mt-1 line-clamp-2 text-sm font-semibold">{data.continue.prompt}</p><span className="mt-3 inline-flex items-center gap-1 text-xs font-bold text-teal-700 dark:text-teal-300">Continue <ArrowRight size={14}/></span></Link> : <p className="mt-3 text-sm text-muted-foreground">Start a set to create your study trail.</p>}</div>
      <div className="rounded-2xl border bg-card p-5"><p className="text-xs font-bold uppercase tracking-widest text-muted-foreground">Revision today</p><p className="mt-3 text-sm text-muted-foreground">{data.summary.due_today ? `${data.summary.due_today} saved revision ${data.summary.due_today === 1 ? "item is" : "items are"} ready for review.` : "Nothing due today—keep building a thoughtful revision queue."}</p><Link href="/theory/revision-queue" className="mt-4 inline-flex items-center gap-2 text-sm font-bold text-amber-700 dark:text-amber-300"><CalendarClock size={16}/>Open revision queue</Link></div>
    </section>
    <section className="grid gap-4 lg:grid-cols-2">{([ ["End of Rotation",rotation], ["End of Year",year] ] as [string, Level[]][]).map(([title, items]) => <div key={String(title)} className="rounded-2xl border bg-card p-5"><div className="flex items-baseline justify-between"><h2 className="font-bold">{title}</h2><span className="text-sm font-bold text-teal-700 dark:text-teal-300">{progress(items as Level[])}%</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-teal-600" style={{ width: `${progress(items as Level[])}%` }}/></div><p className="mt-3 text-xs text-muted-foreground">{(items as Level[]).reduce((n,x)=>n+x.completed,0)} completed · {(items as Level[]).reduce((n,x)=>n+x.total,0)} questions</p><Link href={`/theory/browse?collection=${String(title).includes("Rotation") ? "end_of_rotation" : "end_of_year"}`} className="mt-3 inline-flex text-xs font-bold text-teal-700 dark:text-teal-300">Browse collection</Link></div>)}</section>
    <section className="rounded-2xl border bg-card p-5"><h2 className="font-bold">Recently studied disciplines & sets</h2><div className="mt-3 grid gap-2 sm:grid-cols-2">{data.hierarchy.filter(x=>x.recent_activity).slice(0,6).map(x => <Link key={`${x.discipline_id}-${x.set_id}`} href={href(x as unknown as Item)} className="rounded-xl border p-3 hover:bg-muted"><p className="text-xs font-bold text-teal-700 dark:text-teal-300">{x.collection_title} · {x.discipline_title}</p><p className="mt-1 text-sm font-medium">{x.set_title || "All questions"}</p><p className="mt-1 text-xs text-muted-foreground">{x.read}/{x.total} read · {x.completed} completed · {x.saved} saved · {x.notes} notes</p></Link>) || <p className="text-sm text-muted-foreground">Recent disciplines will appear after your first study action.</p>}</div></section>
  </div>
}
