"use client"
import Link from "next/link"
import { ExternalLink } from "lucide-react"

export type SavedTheoryItem = { id: string; prompt: string; collectionId: string; disciplineId: string; setId: string | null; tags?: string[]; completed?: boolean; collectionTitle?: string; disciplineTitle?: string; setTitle?: string; revisionState?: string }
export const itemHref = (x: SavedTheoryItem) => `/theory/reader?${new URLSearchParams({ collectionId: x.collectionId, disciplineId: x.disciplineId, ...(x.setId ? { setId: x.setId } : {}) })}`
export function ItemMeta({ item }: { item: SavedTheoryItem }) { return <div className="mt-2 flex flex-wrap items-center gap-1.5 text-[10px] font-semibold"><span className="text-muted-foreground">{[item.collectionTitle || item.collectionId, item.disciplineTitle || item.disciplineId, item.setTitle].filter(Boolean).join(" · ")}</span>{item.tags?.slice(0, 3).map(tag => <span key={tag} className="rounded-full bg-muted px-2 py-0.5">#{tag}</span>)}<Link href={itemHref(item)} className="ml-auto inline-flex items-center gap-1 text-teal-700 hover:underline dark:text-teal-300">Open <ExternalLink size={11}/></Link></div> }
export function ItemFilters({ items, value, onChange }: { items: SavedTheoryItem[]; value: string; onChange: (value: string) => void }) { const tags = [...new Set(items.flatMap(x => x.tags || []))]; return <select aria-label="Filter saved questions" value={value} onChange={e => onChange(e.target.value)} className="min-h-10 rounded-lg border bg-background px-3 text-sm"><option value="all">All saved items</option><option value="rotation">End of Rotation</option><option value="year">End of Year</option><option value="completed">Completed</option><option value="incomplete">Not completed</option><option value="revision">In revision</option>{[...new Set(items.map(x=>x.disciplineId))].map(x=><option key={x} value={`discipline:${x}`}>Discipline: {items.find(y=>y.disciplineId===x)?.disciplineTitle || x}</option>)}{[...new Set(items.filter(x=>x.setId).map(x=>x.setId!))].map(x=><option key={x} value={`set:${x}`}>Set: {items.find(y=>y.setId===x)?.setTitle || x}</option>)}{tags.map(x=><option key={x} value={`tag:${x}`}>Tag: {x}</option>)}</select> }
export const matchesFilter = (x: SavedTheoryItem, filter: string) => filter === "all" || (filter === "rotation" && x.collectionId === "end_of_rotation") || (filter === "year" && x.collectionId === "end_of_year") || (filter === "completed" && x.completed) || (filter === "incomplete" && !x.completed) || (filter === "revision" && x.revisionState === "pending") || (filter.startsWith("discipline:") && x.disciplineId === filter.slice(11)) || (filter.startsWith("set:") && x.setId === filter.slice(4)) || (filter.startsWith("tag:") && x.tags?.includes(filter.slice(4)))
