"use client"
import { useState } from "react"
import { useTutorials } from "./TutorialProvider"
export function TutorialSettings() {
  const { replay, reset, records, isPhone } = useTutorials(); const [resetting, setResetting] = useState(false)
  const mcqId = isPhone ? "mcq_qbank_phone_intro" : "mcq_qbank_desktop_intro"
  const theoryId = isPhone ? "theory_vault_phone_intro" : "theory_vault_desktop_intro"
  return <section className="rounded-2xl border border-border bg-card p-5 shadow-sm" aria-labelledby="guided-tours-title"><h2 id="guided-tours-title" className="font-semibold">Guided tours</h2><p className="mt-1 text-sm text-muted-foreground">Replay the tutorial designed for this {isPhone ? "phone" : "desktop"} layout without changing learning statistics, inventory, streaks, or Nexus Points.</p><div className="mt-4 flex flex-wrap gap-2"><button type="button" className="min-h-11 rounded-xl border px-4 text-sm font-semibold hover:bg-muted" onClick={() => void replay(mcqId)}>Replay MCQ {isPhone ? "phone" : "desktop"} tutorial</button><button type="button" className="min-h-11 rounded-xl border px-4 text-sm font-semibold hover:bg-muted" onClick={() => void replay(theoryId)}>Replay Theory {isPhone ? "phone" : "desktop"} tutorial</button><button type="button" className="min-h-11 rounded-xl px-4 text-sm font-semibold text-destructive hover:bg-destructive/10" onClick={() => setResetting(true)}>Reset tutorial progress</button></div>{resetting && <div role="alertdialog" className="mt-3 rounded-xl border p-3"><p className="text-sm">Reset desktop and phone tour positions? Your study and economy data are unaffected.</p><div className="mt-2 flex gap-2"><button className="min-h-11 rounded-lg border px-4" onClick={() => setResetting(false)}>Cancel</button><button className="min-h-11 rounded-lg bg-destructive px-4 text-destructive-foreground" onClick={() => { void reset(); setResetting(false) }}>Reset tours</button></div></div>}<div className="mt-3 grid gap-1 text-xs text-muted-foreground sm:grid-cols-2"><p>MCQ desktop: {records.mcq_qbank_desktop_intro.status.replaceAll("_", " ")} · phone: {records.mcq_qbank_phone_intro.status.replaceAll("_", " ")}</p><p>Theory desktop: {records.theory_vault_desktop_intro.status.replaceAll("_", " ")} · phone: {records.theory_vault_phone_intro.status.replaceAll("_", " ")}</p></div></section>
}
