"use client"

import { useCallback, useEffect, useState } from "react"
import { CalendarClock, Download, Loader2, Plus, RefreshCw, RotateCcw, ShieldCheck, X } from "lucide-react"

type Season={id:string;name:string;economy_version:string;status:"planned"|"active"|"closed";starts_at:string;ends_at:string|null;opening_grant:number;member_count:number;currency_supply:string;currency_earned:string;cutover_completed_at:string|null}
type Data={seasons:Season[];activeSeason:Season|null;dryRunReport:{approved_users:number;ineligible_users:number}}
const control="min-h-11 rounded-xl border border-border bg-background px-3 text-sm outline-none focus:ring-2 focus:ring-primary/25"
const button="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl px-4 text-sm font-bold transition-colors disabled:opacity-40"

export function EconomySeasonsWorkspace({canReset}:{canReset:boolean}){
  const [data,setData]=useState<Data|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[notice,setNotice]=useState("")
  const [creating,setCreating]=useState(false),[activating,setActivating]=useState<Season|null>(null),[busy,setBusy]=useState(false)
  const [name,setName]=useState(""),[version,setVersion]=useState(""),[openingGrant,setOpeningGrant]=useState(500),[startsAt,setStartsAt]=useState("")
  const [confirmation,setConfirmation]=useState("")
  const load=useCallback(async()=>{setLoading(true);setError("");try{const response=await fetch("/api/admin/economy-seasons",{cache:"no-store"});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error??"Unable to load economy seasons.");setData(body)}catch(cause){setError(cause instanceof Error?cause.message:"Unable to load economy seasons.")}finally{setLoading(false)}},[])
  useEffect(()=>{void load()},[load])
  const request=async(body:Record<string,unknown>)=>{setBusy(true);setError("");setNotice("");try{const response=await fetch("/api/admin/economy-seasons",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error??"Season operation failed.");setData(result);setNotice(body.action==="create"?"Planned season created.":"Season reset completed and opening balances verified.");setCreating(false);setActivating(null);setConfirmation("")}catch(cause){setError(cause instanceof Error?cause.message:"Season operation failed.")}finally{setBusy(false)}}
  if(loading&&!data)return <div className="grid min-h-64 place-items-center"><Loader2 className="animate-spin text-primary"/></div>
  if(!data)return <div role="alert" className="rounded-xl border border-destructive/30 bg-destructive/10 p-5 text-sm text-destructive"><p>{error||"Economy seasons are unavailable."}</p><button onClick={()=>void load()} className={`${button} mt-4 border border-destructive/30`}><RefreshCw size={16}/>Retry</button></div>
  return <main className="mx-auto w-full max-w-6xl space-y-6"><header className="flex flex-col gap-4 border-b border-border pb-6 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-primary">Economy control</p><h1 className="mt-1 text-3xl font-bold">Economy Seasons</h1><p className="mt-2 max-w-2xl text-sm text-muted-foreground">Plan the next season, inspect the reset impact, and start it with an archived, verified cutover.</p></div><div className="flex flex-wrap gap-2"><a href="/api/admin/economy-seasons?download=1" className={`${button} border border-border`}><Download size={16}/>Dry-run report</a><button onClick={()=>void load()} className={`${button} border border-border`}><RefreshCw size={16}/>Refresh</button>{canReset&&<button onClick={()=>setCreating(true)} className={`${button} bg-primary text-primary-foreground`}><Plus size={16}/>Plan season</button>}</div></header>
    {error&&<div role="alert" className="rounded-xl border border-destructive/30 bg-destructive/10 p-3 text-sm text-destructive">{error}</div>}{notice&&<div role="status" className="rounded-xl border border-emerald-500/30 bg-emerald-500/10 p-3 text-sm text-emerald-700">{notice}</div>}
    <section className="grid gap-3 sm:grid-cols-3"><div className="rounded-xl border border-border bg-card p-4"><p className="text-xs text-muted-foreground">Active season</p><p className="mt-1 text-xl font-bold">{data.activeSeason?.name??"None"}</p></div><div className="rounded-xl border border-border bg-card p-4"><p className="text-xs text-muted-foreground">Eligible students</p><p className="mt-1 text-xl font-bold">{data.dryRunReport.approved_users}</p></div><div className="rounded-xl border border-border bg-card p-4"><p className="text-xs text-muted-foreground">Current spendable supply</p><p className="mt-1 text-xl font-bold">{Number(data.activeSeason?.currency_supply??0).toLocaleString()} NP</p></div></section>
    <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{data.seasons.map(season=><article key={season.id} className={`rounded-2xl border bg-card p-5 ${season.status==="active"?"border-primary/50 ring-1 ring-primary/10":"border-border"}`}><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-widest text-muted-foreground">{season.economy_version}</p><h2 className="mt-1 text-xl font-bold">{season.name}</h2></div><span className="rounded-full border border-border px-2.5 py-1 text-[10px] font-bold uppercase">{season.status}</span></div><dl className="mt-5 grid grid-cols-2 gap-3 text-sm"><div><dt className="text-xs text-muted-foreground">Opening grant</dt><dd className="font-bold">{season.opening_grant} NP</dd></div><div><dt className="text-xs text-muted-foreground">Members</dt><dd className="font-bold">{season.member_count}</dd></div><div><dt className="text-xs text-muted-foreground">Spendable supply</dt><dd className="font-bold">{Number(season.currency_supply).toLocaleString()} NP</dd></div><div><dt className="text-xs text-muted-foreground">Total earned</dt><dd className="font-bold">{Number(season.currency_earned).toLocaleString()} NP</dd></div><div><dt className="text-xs text-muted-foreground">{season.status==="planned"?"Planned start":"Started"}</dt><dd className="font-bold">{new Date(season.starts_at).toLocaleString()}</dd></div></dl>{season.cutover_completed_at&&<p className="mt-4 flex items-center gap-2 border-t border-border pt-4 text-xs text-emerald-600"><ShieldCheck size={15}/>Cutover verified</p>}{season.status==="planned"&&canReset&&<button onClick={()=>setActivating(season)} className={`${button} mt-5 w-full border border-primary/30 text-primary`}><RotateCcw size={16}/>Start and reset economy</button>}</article>)}</section>
    {!canReset&&<p className="rounded-xl border border-border bg-muted/30 p-4 text-sm text-muted-foreground">Season resets are restricted to super administrators. You can inspect and download the dry-run report.</p>}
    {creating&&<div className="fixed inset-0 z-[100] grid place-items-center bg-black/50 p-4"><div role="dialog" aria-modal="true" aria-label="Plan economy season" className="w-full max-w-lg rounded-2xl border border-border bg-card p-5"><div className="flex justify-between"><div><h2 className="text-xl font-bold">Plan next season</h2><p className="mt-1 text-sm text-muted-foreground">Planning does not reset balances or activate the season.</p></div><button onClick={()=>setCreating(false)}><X/></button></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-xs font-bold text-muted-foreground">Season name<input value={name} onChange={event=>setName(event.target.value)} placeholder="Season 2" className={`${control} mt-1 w-full text-foreground`}/></label><label className="text-xs font-bold text-muted-foreground">Economy version<input value={version} onChange={event=>setVersion(event.target.value)} placeholder="3.0" className={`${control} mt-1 w-full text-foreground`}/></label><label className="text-xs font-bold text-muted-foreground">Opening grant<input type="number" min={0} max={100000} value={openingGrant} onChange={event=>setOpeningGrant(Number(event.target.value))} className={`${control} mt-1 w-full text-foreground`}/></label><label className="text-xs font-bold text-muted-foreground">Planned start<input type="datetime-local" value={startsAt} onChange={event=>setStartsAt(event.target.value)} className={`${control} mt-1 w-full text-foreground`}/></label></div><div className="mt-5 flex justify-end gap-2"><button onClick={()=>setCreating(false)} className={`${button} border border-border`}>Cancel</button><button disabled={busy||name.trim().length<3||!version.trim()} onClick={()=>void request({action:"create",name,economyVersion:version,openingGrant,startsAt:startsAt||new Date().toISOString()})} className={`${button} bg-primary text-primary-foreground`}>{busy&&<Loader2 size={16} className="animate-spin"/>}Create planned season</button></div></div></div>}
    {activating&&<div className="fixed inset-0 z-[100] grid place-items-center bg-black/50 p-4"><div role="dialog" aria-modal="true" aria-label="Reset economy season" className="w-full max-w-lg rounded-2xl border border-destructive/40 bg-card p-5"><CalendarClock className="text-destructive"/><h2 className="mt-3 text-xl font-bold">Start {activating.name}?</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">This archives the current season, closes it, resets seasonal balances and streaks, creates verified opening wallets for {data.dryRunReport.approved_users} eligible students, and records an audited cutover. Purchases and cosmetics remain stored.</p><label className="mt-4 block text-sm">Type <b>START {activating.name.toUpperCase()}</b><input value={confirmation} onChange={event=>setConfirmation(event.target.value)} className={`${control} mt-2 w-full`}/></label><div className="mt-5 flex justify-end gap-2"><button onClick={()=>{setActivating(null);setConfirmation("")}} className={`${button} border border-border`}>Cancel</button><button disabled={busy||confirmation!==`START ${activating.name.toUpperCase()}`} onClick={()=>void request({action:"activate",seasonId:activating.id,confirmation})} className={`${button} bg-destructive text-destructive-foreground`}>{busy&&<Loader2 size={16} className="animate-spin"/>}Archive and start season</button></div></div></div>}
  </main>
}
